/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    gowns: Gown;
    media: Media;
    inquiries: Inquiry;
    reservations: Reservation;
    faqs: Faq;
    testimonials: Testimonial;
    'real-moms': RealMom;
    'blog-posts': BlogPost;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    gowns: GownsSelect<false> | GownsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'real-moms': RealMomsSelect<false> | RealMomsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The collection. The availability badge shown on the site is the “Availability status” field in the sidebar - keep it current after every booking and return.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gowns".
 */
export interface Gown {
  id: number;
  /**
   * The badge shown on the site. Set “On rental” when a gown goes out and switch it back to “Available” only after it is returned, inspected AND cleaned - that habit is the buffer between rentals.
   */
  availabilityStatus: 'available' | 'limited' | 'on_rental' | 'contact_to_confirm';
  /**
   * Shown with the badge, e.g. “Back after Nov 20”.
   */
  nextAvailableNote?: string | null;
  availabilityUpdatedAt?: string | null;
  published?: boolean | null;
  /**
   * Gowns with a movement video automatically appear first in the homepage featured section (and in “See them in motion”) - tick this to feature additional gowns.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first in the collection.
   */
  displayOrder?: number | null;
  /**
   * The gown’s web address: /gowns/[slug]. Filled automatically from the name.
   */
  slug: string;
  condition?: {
    conditionStatus?: ('excellent' | 'good' | 'needs_repair' | 'retired') | null;
    lastInspectedAt?: string | null;
    conditionNotes?: string | null;
  };
  name: string;
  /**
   * One evocative sentence used on cards and as the meta-description source, e.g. “Regal ruby-red lace, made for a grand moment.”
   */
  shortDescription: string;
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  rentalPrice5Day: number;
  rentalPrice10Day: number;
  categories: ('photoshoot' | 'baby-shower')[];
  /**
   * “For South-Asian shoots” gowns also appear in the South Asian collection page; “Classic / Western” gowns appear in the Western collection page. A styling grouping, not a garment type.
   */
  cultureEdit: 'classic' | 'south-asian-shoot';
  styleTags?: ('flowing' | 'fitted' | 'dramatic' | 'minimal')[] | null;
  /**
   * E.g. “Ruby red”, “Dusty rose”.
   */
  colorPrimary: string;
  colorFamily: 'neutral' | 'pastel' | 'warm' | 'jewel' | 'bold';
  fabric?: string | null;
  /**
   * Occasion, setting and mood, e.g. “Grand photoshoots, indoor or ornate settings, regal drama”.
   */
  bestFor?: string | null;
  /**
   * The consistent catalogue image used on cards - same crop, lighting and background across every gown keeps the grid premium.
   */
  primaryImage?: (number | null) | Media;
  images?:
    | {
        image: number | Media;
        viewType?: ('front' | 'side' | 'back' | 'detail') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Not every gown needs one - gowns without a video simply show their photos. Upload a compressed mp4 (720p, roughly 3–8 MB for a 6–10 second clip - see SETUP.md “Adding your videos”) plus a poster frame. Gowns with a video appear automatically in the homepage “See them in motion” strip.
   */
  video?: {
    file?: (number | null) | Media;
    poster?: (number | null) | Media;
  };
  /**
   * Only photos with the consent box ticked are ever shown on the site.
   */
  ugcPhotos?:
    | {
        image: number | Media;
        caption?: string | null;
        consent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Leave empty to use “[Name] - Maternity Gown Rental | Mummy2Be”.
     */
    seoTitle?: string | null;
    /**
     * Leave empty to use “Rent [Name] - [one-liner] One size fits every bump…”.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * All gown photos and movement videos live here. Upload files, give each a clear description (alt text), then attach them to gowns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe only what is actually in the photo, e.g. “Dusty-rose flowing maternity gown with a full train, photographed on a model at an outdoor shoot”. Our catalog shots are of a hired model, so never describe her as a customer or an expecting mom - that language belongs only to the consented Real moms gallery. Used for accessibility and SEO.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Every rental request lands here the moment it is sent - reply the same day on the customer’s preferred channel. Create a Reservation from an inquiry once you confirm dates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  status?: ('new' | 'replied' | 'reservation_created' | 'closed') | null;
  inquiryType?: ('customer' | 'photographer') | null;
  submittedAt?: string | null;
  sourcePage?: string | null;
  fullName: string;
  phone: string;
  email: string;
  preferredContactMethod: 'call' | 'text' | 'whatsapp' | 'email';
  city?: string | null;
  province?:
    | (
        | 'Ontario'
        | 'Quebec'
        | 'British Columbia'
        | 'Alberta'
        | 'Manitoba'
        | 'Saskatchewan'
        | 'Nova Scotia'
        | 'New Brunswick'
        | 'Newfoundland and Labrador'
        | 'Prince Edward Island'
        | 'Northwest Territories'
        | 'Yukon'
        | 'Nunavut'
      )
    | null;
  gowns?: (number | Gown)[] | null;
  /**
   * Snapshot of the gown names at the time of the request.
   */
  gownNames?: string | null;
  eventDate?: string | null;
  rentalPeriod?: ('5_day' | '10_day') | null;
  preferredRentalDates?: string | null;
  deliveryOrPickupPreference?: ('canada_post' | 'local_gta') | null;
  sizingQuestions?: string | null;
  message?: string | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your behind-the-scenes record of each rental, from first contact to deposit refund. Customers never see this - it exists so nothing is forgotten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  status:
    | 'inquiry_received'
    | 'contacted'
    | 'confirmed'
    | 'paid'
    | 'shipped'
    | 'active_rental'
    | 'returned'
    | 'inspected'
    | 'deposit_refunded'
    | 'completed'
    | 'on_hold'
    | 'cancelled';
  customerName: string;
  gown?: (number | null) | Gown;
  inquiry?: (number | null) | Inquiry;
  eventDate?: string | null;
  rentalPeriod?: ('5_day' | '10_day') | null;
  rentalStartDate?: string | null;
  rentalEndDate?: string | null;
  totalAgreed?: number | null;
  deposit?: {
    amount?: number | null;
    depositStatus?: ('not_collected' | 'held' | 'refunded' | 'partially_withheld' | 'withheld') | null;
    collectedAt?: string | null;
    refundedAt?: string | null;
    withheldAmount?: number | null;
    withheldReason?: string | null;
  };
  shipping?: {
    method?: ('canada_post' | 'local_gta_delivery' | 'local_gta_pickup') | null;
    costCharged?: number | null;
    outboundTracking?: string | null;
    returnTracking?: string | null;
    shippedAt?: string | null;
    deliveredAt?: string | null;
    returnLabelSentAt?: string | null;
    returnedAt?: string | null;
  };
  condition?: {
    preRentalCondition?: string | null;
    postRentalCondition?: string | null;
    damageNotes?: string | null;
    inspectionStatus?: ('pending' | 'passed' | 'issues_found') | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions and answers shown on the FAQ page (and previewed on the homepage and gown pages).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  group: 'gowns-fit' | 'booking-availability' | 'payment-deposit' | 'shipping-returns' | 'about-us';
  /**
   * Lower numbers appear first within their group.
   */
  displayOrder?: number | null;
  featuredOnHome?: boolean | null;
  showOnProduct?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real customer reviews only - with their permission. Testimonial sections on the site appear automatically once entries exist here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  quote: string;
  /**
   * E.g. “Maternity photoshoot, 32 weeks - Toronto”.
   */
  context?: string | null;
  photo?: (number | null) | Media;
  gown?: (number | null) | Gown;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real customer shoot photos. A photo only appears on the site once its consent box is ticked - never publish without permission.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "real-moms".
 */
export interface RealMom {
  id: number;
  name: string;
  photo: number | Media;
  /**
   * E.g. “34 weeks”.
   */
  weeks?: string | null;
  /**
   * E.g. “golden-hour photoshoot, Mississauga”.
   */
  occasion?: string | null;
  gown?: (number | null) | Gown;
  consent: boolean;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The Style Journal. Every article should link readers to at least one collection page and one gown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL: /blog/[slug]
   */
  slug: string;
  published?: boolean | null;
  publishedAt?: string | null;
  /**
   * Shown on the article card and used as the default meta description.
   */
  excerpt: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    seoTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Editable content used by specific pages: “home” (hero photo), “about-story” (Our Story + behind-the-scenes video), “rental-terms” (Rental Terms). Do not change the slugs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Only used by the “home” entry: upload the hero photo (a gown shot, studio or consented customer) and the homepage switches from the art treatment to full-bleed photography.
   */
  heroImage?: (number | null) | Media;
  /**
   * Only used by the “about-story” entry: upload the single behind-the-scenes clip (compressed mp4) and a poster frame, and it appears in the “behind the scenes” section of the About page.
   */
  btsVideo?: {
    file?: (number | null) | Media;
    poster?: (number | null) | Media;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'gowns';
        value: number | Gown;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'real-moms';
        value: number | RealMom;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gowns_select".
 */
export interface GownsSelect<T extends boolean = true> {
  availabilityStatus?: T;
  nextAvailableNote?: T;
  availabilityUpdatedAt?: T;
  published?: T;
  featured?: T;
  displayOrder?: T;
  slug?: T;
  condition?:
    | T
    | {
        conditionStatus?: T;
        lastInspectedAt?: T;
        conditionNotes?: T;
      };
  name?: T;
  shortDescription?: T;
  fullDescription?: T;
  rentalPrice5Day?: T;
  rentalPrice10Day?: T;
  categories?: T;
  cultureEdit?: T;
  styleTags?: T;
  colorPrimary?: T;
  colorFamily?: T;
  fabric?: T;
  bestFor?: T;
  primaryImage?: T;
  images?:
    | T
    | {
        image?: T;
        viewType?: T;
        id?: T;
      };
  video?:
    | T
    | {
        file?: T;
        poster?: T;
      };
  ugcPhotos?:
    | T
    | {
        image?: T;
        caption?: T;
        consent?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        seoTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  status?: T;
  inquiryType?: T;
  submittedAt?: T;
  sourcePage?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  preferredContactMethod?: T;
  city?: T;
  province?: T;
  gowns?: T;
  gownNames?: T;
  eventDate?: T;
  rentalPeriod?: T;
  preferredRentalDates?: T;
  deliveryOrPickupPreference?: T;
  sizingQuestions?: T;
  message?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  status?: T;
  customerName?: T;
  gown?: T;
  inquiry?: T;
  eventDate?: T;
  rentalPeriod?: T;
  rentalStartDate?: T;
  rentalEndDate?: T;
  totalAgreed?: T;
  deposit?:
    | T
    | {
        amount?: T;
        depositStatus?: T;
        collectedAt?: T;
        refundedAt?: T;
        withheldAmount?: T;
        withheldReason?: T;
      };
  shipping?:
    | T
    | {
        method?: T;
        costCharged?: T;
        outboundTracking?: T;
        returnTracking?: T;
        shippedAt?: T;
        deliveredAt?: T;
        returnLabelSentAt?: T;
        returnedAt?: T;
      };
  condition?:
    | T
    | {
        preRentalCondition?: T;
        postRentalCondition?: T;
        damageNotes?: T;
        inspectionStatus?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  group?: T;
  displayOrder?: T;
  featuredOnHome?: T;
  showOnProduct?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  context?: T;
  photo?: T;
  gown?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "real-moms_select".
 */
export interface RealMomsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  weeks?: T;
  occasion?: T;
  gown?: T;
  consent?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  publishedAt?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  btsVideo?:
    | T
    | {
        file?: T;
        poster?: T;
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}